spring:
  profiles.active: local
---
spring:
  profiles: default
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/tickettoridegame?autoReconnect=true
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
---
spring:
  profiles: local

server:
  port: 8080
---
spring:
  profiles: cloud
datasource:
  service-name: TTR_MySQL_Game 
  
